Enable XYZ chunking at conversion
czbiohub-sf/iohub pull request #178
Opened 2023-08-22 00:09 UTC by ieivanov

This PR enables XYZ chunking at zarr conversion and speeds up `ndtiff` conversion following [this](https://github.com/czbiohub-sf/compmicro-sandbox/blob/master/iohub_scripts/convert/convert_isim_fish.py) example.

Fixes #176, Fixes #177 

To use, call `iohub convert -i /path/to/input/ -o /path/to/output.zarr/ --chunks XYZ`. Z stacks may be split into multiple chunks if they are larger than `MAX_CHUNK_SIZE` bytes.

We should use this code to convert future datasets and we should also re-convert older large datasets to reduce the number of small files on our storage.

Let's build on this code and make the converter work well. So far, I've tested it only with `pytest` and latest mantis `ndtiff` datasets. Currently, the converter effectively splits into two paths, depending on whether you're converting a `ndtiff` dataset or now. I believe @ziw-liu's intension is to make all readers return a lazy dask array, similarly to how `ndtiff` works. This can be a starting point to a universal converter following the revamp of the readers as part of the Universal API.

2023-08-22 00:29 UTC, ziw-liu commented on iohub/convert.py
> +            for p_idx in tqdm(range(self.p), bar_format=bar_format):
Can this separate path be contained in its own method?

2023-08-22 00:29 UTC, ziw-liu commented on iohub/convert.py
> +                        "filling with zeros. Raw data may be is incomplete."
```suggestion
                        "filling with zeros. Raw data may be incomplete."
```

2023-08-23 04:24 UTC, edyoshikun approved these changes
LGTM!

2023-08-23 04:56 UTC, talonchandler approved these changes

2023-08-23 04:56 UTC, talonchandler commented on iohub/cli/cli.py
> +    "dimensions.",
Am I reading correctly that 'XYZ' chunks will be clipped to 500 MB? If yes, I think this is a good choice and should be documented:

```suggestion
    "dimensions. If 'XYZ', chunk size will be limited to 500 MB.",
```

2023-08-23 05:09 UTC, ziw-liu requested changes
Holding for https://github.com/czbiohub-sf/iohub/pull/178#discussion_r1300781300

2023-08-23 22:42 UTC, ziw-liu approved these changes

2023-08-24 18:32 UTC, ieivanov commented
Tested that missing timepoints are now handled correctly, ready to merge

2023-08-26 00:52 UTC, merged